# Generated by Django 5.1.3 on 2025-04-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_quiz_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('quiz_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('is_right', models.IntegerField()),
            ],
            options={
                'unique_together': {('username', 'quiz_id', 'question_id')},
            },
        ),
    ]
