# Generated by Django 5.1.3 on 2025-04-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer_text',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
