# Generated by Django 5.1.3 on 2025-04-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_useranswer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author_id_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
