# Generated by Django 5.1.3 on 2025-06-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_quiz_author_id_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['id'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
