# Generated by Django 5.1.3 on 2025-06-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_answer_options_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Răspuns', 'verbose_name_plural': 'Răspunsuri'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['id'], 'verbose_name': 'Chestionar', 'verbose_name_plural': 'Chestionare'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
