# Generated by Django 5.1.3 on 2025-06-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_answer_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
