# Generated by Django 5.1.3 on 2025-06-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code_created_at',
        ),
    ]
