# Generated by Django 5.1.3 on 2025-06-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_code_created_at_user_verification_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
    ]
