# Generated by Django 5.1.3 on 2025-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('confirmation_code', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
